# Generated by Django 6.0 on 2026-01-13 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medicalcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('card_prefix', models.CharField(max_length=10)),
                ('card_number', models.CharField(max_length=50)),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinic.medicalcard')),
            ],
        ),
    ]
