# Generated by Django 6.0 on 2026-01-13 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_medicaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocumentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=100, verbose_name='Код поля')),
                ('field_name', models.CharField(max_length=255, verbose_name='Наименование поля')),
                ('value', models.TextField(verbose_name='Значение')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='clinic.medicaldocument')),
            ],
            options={
                'unique_together': {('document', 'field_code')},
            },
        ),
    ]
