# Generated by Django 6.0 on 2026-01-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_medicaldocumentfieldvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocument',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='card_prefix',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('PRIMARY_VISIT', 'Первичный приём'), ('HEAD_DOCTOR_REVIEW', 'Осмотр с заведующим'), ('PREOPERATIVE_EPICRISIS', 'Предоперационный эпикриз'), ('OPERATION', 'Протокол операции'), ('DISCHARGE_EPICRISIS', 'Выписной эпикриз'), ('UNKNWOWN', 'ПУТСЫШКК')], default='UNKNWOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('SIGNED', 'Подписан')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
